name: Stage
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "develop", "staging" ]
env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX:PATH=${{github.workspace}}/project

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Install
        run: cmake --install ${{github.workspace}}/build

      - name: Store binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: |
            ${{github.workspace}}/project
  tests:
    name: App tests
    needs: build
    runs-on: ubuntu-latest
    container:
      image: jamalabo1/general_images:valgrind
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: binaries

      - name: Unit Tests
        working-directory: bin
        run: |
          chmod 755 ./technion-234124_tests_exc
          ./technion-234124_tests_exc


      - name: Case tests
        working-directory: bin
        run: |
          python3 engine/main.py

      - name: Archive Results
        uses: actions/upload-artifact@v4
        with:
          name: tests
          path: ./bin/*test*/*.out

      - name: Valgrind Test
        working-directory: bin
        run: |
          ls
          python3 engine/main.py --valgrind
          

